 id |            name            |                                                                                                                                                                           description                                                                                                                                                                           |      image       | price_cents | quantity |         created_at         |         updated_at         | category_id 
----+----------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------+-------------+----------+----------------------------+----------------------------+-------------
  1 | Men's Classy shirt         | Mumblecore xoxo taxidermy readymade. Cronut street chia truffaut selfies tattooed. Flannel letterpress pbr&b beard heirloom celiac. Poutine semiotics roof offal direct trade. Street park twee vinegar authentic +1. Jean shorts schlitz microdosing authentic bushwick iphone seitan.                                                                         | apparel1.jpg     |        6499 |       10 | 2018-06-21 21:59:32.776283 | 2018-06-21 21:59:32.776283 |           1
  2 | Women's Zebra pants        | Ramps photo booth banh mi. Fanny pack gentrify yolo. Sriracha green juice pop-up. Gentrify thundercats twee. Heirloom drinking meditation skateboard austin sartorial banh mi.                                                                                                                                                                                  | apparel2.jpg     |       12499 |       18 | 2018-06-21 21:59:33.074072 | 2018-06-21 21:59:33.074072 |           1
  3 | Hipster Hat                | Diy meditation cray pitchfork irony cold-pressed twee kombucha. Pop-up shabby chic plaid brunch flexitarian biodiesel loko raw denim. Pug leggings pour-over cardigan gluten-free neutra +1. Venmo literally yr sartorial fashion axe meh. Chia bushwick xoxo art party cleanse fixie. Chicharrones fap chambray yolo drinking.                                 | apparel3.jpg     |        3449 |        4 | 2018-06-21 21:59:33.427657 | 2018-06-21 21:59:33.427657 |           1
  4 | Hipster Socks              | Wes anderson semiotics ethical pbr&b mixtape neutra umami. Gastropub put a bird on it yr next level. Ethical beard ramps. Aesthetic health tilde you probably haven't heard of them sriracha cray synth. Normcore swag taxidermy shabby chic lumbersexual bushwick flannel quinoa. Beard marfa jean shorts.                                                     | apparel4.jpg     |        2500 |        8 | 2018-06-21 21:59:34.760112 | 2018-06-21 21:59:34.760112 |           1
  5 | Russian Spy Shoes          | Kickstarter mustache franzen fap intelligentsia hashtag. Tousled pug gluten-free franzen pickled literally. Chicharrones semiotics tofu goth. Authentic messenger bag jean shorts tacos. Disrupt deep v food truck yolo art party forage pitchfork. Kitsch photo booth humblebrag.                                                                              | apparel5.jpg     |      122500 |        8 | 2018-06-21 21:59:35.486111 | 2018-06-21 21:59:35.486111 |           1
  6 | Human Feet Shoes           | Shoreditch portland skateboard gastropub hammock direct trade lumbersexual brooklyn. Vhs vegan portland leggings pabst synth. Forage dreamcatcher cold-pressed lo-fi slow-carb squid roof. Echo portland gastropub yr celiac.                                                                                                                                   | apparel6.jpg     |       22450 |       82 | 2018-06-21 21:59:36.023042 | 2018-06-21 21:59:36.023042 |           1
  7 | Modern Skateboards         | +1 ramps blog meggings tumblr artisan tote bag. Bitters offal organic post-ironic 8-bit sartorial celiac small batch. Xoxo chambray irony cleanse keytar. Stumptown small batch tote bag. Bicycle rights letterpress yolo.                                                                                                                                      | electronics1.jpg |       16449 |       40 | 2018-06-21 21:59:36.677711 | 2018-06-21 21:59:36.677711 |           2
  8 | Hotdog Slicer              | Hammock fanny pack cornhole wolf organic squid. Heirloom migas literally fanny pack post-ironic 8-bit gastropub forage. Portland goth 8-bit austin mumblecore street. Tote bag mumblecore beard cliche. Before they sold out pour-over hammock chartreuse.                                                                                                      | electronics2.jpg |        2600 |        3 | 2018-06-21 21:59:38.22023  | 2018-06-21 21:59:38.22023  |           2
  9 | World's Largest Smartwatch | Messenger bag single-origin coffee paleo bespoke park taxidermy skateboard. Pabst heirloom meggings humblebrag irony cronut taxidermy. Retro gentrify crucifix mumblecore chambray neutra semiotics. Seitan kinfolk franzen literally typewriter keffiyeh portland etsy. Iphone stumptown jean shorts venmo umami blog art party. Bushwick kale chips keffiyeh. | electronics3.jpg |      202629 |       32 | 2018-06-21 21:59:39.07797  | 2018-06-21 21:59:39.07797  |           2
 10 | Optimal Sleeping Bed       | Truffaut keytar distillery aesthetic kale chips hammock. Retro actually mlkshk franzen cliche. Vinegar skateboard typewriter knausgaard authentic literally distillery gentrify. Synth bespoke try-hard. Semiotics gluten-free tacos retro. Bitters mlkshk authentic fingerstache you probably haven't heard of them.                                           | furniture1.jpg   |      305200 |      320 | 2018-06-21 21:59:39.659137 | 2018-06-21 21:59:39.659137 |           3
 11 | Electric Chair             | Bitters 8-bit tofu kogi franzen. Letterpress lumbersexual sriracha blue bottle jean shorts cardigan. Blog venmo selvage. Portland narwhal drinking kombucha. Chillwave chambray post-ironic food truck sartorial.                                                                                                                                               | furniture2.jpg   |       98765 |        2 | 2018-06-21 21:59:40.687159 | 2018-06-21 21:59:40.687159 |           3
 12 | Red Bookshelf              | Crucifix master bitters diy. Photo booth tofu polaroid chartreuse chillwave franzen mlkshk. Chicharrones etsy hammock. Pickled fap heirloom hoodie squid gluten-free. Pitchfork microdosing slow-carb health diy franzen. Ethical semiotics freegan cliche yolo gentrify.                                                                                       | furniture3.jpg   |      248375 |        0 | 2018-06-21 21:59:41.943622 | 2018-06-21 21:59:41.943622 |           3
(12 rows)

